# Fast running checks for pull-requests

name: Pull-Request Checks
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

on:
  pull_request

jobs:
  check-versions:
    if: github.base_ref == 'master'
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/checkVersions.yml@master
    with:
      botName: Eclipse JDT Bot
      botMail: jdt-bot@eclipse.org
